version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"
    networks:
      - hippo-api-http-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - hippo-api-http-network

networks:
  hippo-api-http-network:
    name: hippo-api-http
