name: Scala CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "./**.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "./**.md"

permissions:
  contents: read

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      all-relevant-changed: ${{ steps.changed-files-yaml.outputs.all-relevant_any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get all relevant files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            all-relevant:
              - '**'
              - '!**.md'
  build:
    runs-on: ubuntu-latest
    needs: [check-changes]
    if: needs.check-changes.outputs.all-relevant-changed == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Use coursier cache
        uses: coursier/cache-action@v6.4.3

      - name: Set up coursier with JDK 20 temurin
        uses: coursier/setup-action@v1.3.3
        with:
          jvm: temurin:20
          apps: sbtn

      - name: Run unit and integration tests
        run: sbt test

      - name: Start docker compose
        run: cd ./docker && docker compose up -d

      - name: Run app in background
        run: sbt run < /dev/null & SBT_PID=$!

      - name: Wait until health check is HTTP 200
        run: ./wait.sh

      - name: Run e2e tests
        run: cd ./e2e && npm install && sleep 2 && npm test
        # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    # - name: Upload dependency graph
    #   uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
