name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      all-relevant-changed: ${{ steps.changed-files-yaml.outputs.all-relevant_any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get all relevant files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          since_last_remote_commit: 'true'
          files_yaml: |
            all-relevant:
              - '**'
              - '!**.md'
  build:
    runs-on: ubuntu-latest
    needs: [check-changes]
    if: needs.check-changes.outputs.all-relevant-changed == 'true'

    steps:
      - uses: actions/checkout@v4
